# Generated by Django 4.2.4 on 2023-11-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_alter_img_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_form',
            name='img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.img'),
        ),
    ]
