# Generated by Django 4.2.4 on 2023-11-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_applicant_form_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_form',
            name='img',
        ),
        migrations.AddField(
            model_name='applicant_form',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, to='human_resource.img'),
        ),
    ]
