# Generated by Django 4.2.4 on 2023-11-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0006_remove_applicant_form_img_applicant_form_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_form',
            name='img',
        ),
    ]
