# Generated by Django 4.2.4 on 2023-11-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0007_remove_applicant_form_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_form',
            name='document',
        ),
    ]
