# Generated by Django 4.2.4 on 2023-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0009_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stat',
            name='hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
